---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: gitlab
  namespace: kube-ops
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`git.mzone.me`)
    kind: Rule
    services:
    - name: gitlab
      port: 80
  # tls:
  #   certResolver: default

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: jenkins2
  namespace: kube-ops
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`jenkins2.mzone.me`)
    kind: Rule
    services:
    - name: jenkins2
      port: 8080

---
# apiVersion: traefik.containo.us/v1alpha1
# kind: IngressRoute
# metadata:
#   name: harbor
#   namespace: kube-ops
# spec:
#   entryPoints:
#     - websecure
#   routes:
#   - match: Host(`registry.mzone.me`)
#     kind: Rule
#     services:
#     - name: harbor
#       port: 443
#   tls:
#     certResolver: default