apiVersion: apps/v1
kind: Deployment
metadata:
  name: host-pvc
spec:
  selector:
    matchLabels:
      app: host-pvc
  template:
    metadata:
      labels:
        app: host-pvc
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
          name: web
      #   volumeMounts:
      #   - name: www
      #     mountPath: /usr/share/nginx/html
      # volumes:
      # - name: www
      #   persistentVolumeClaim:
      #     claimName: example-local-claim

---

apiVersion: v1
kind: Service
metadata:
  name: host-pvc
spec:
  selector:
    app: host-pvc
  type: NodePort
  ports:
  - port: 80
    targetPort: web
  