apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-pvc
spec:
  selector:
    matchLabels:
      app: local-pvc
  template:
    metadata:
      labels:
        app: local-pvc
    spec:
      nodeSelector: 
        kubernetes.io/hostname: ip-172-26-7-117
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
          name: web
      #   volumeMounts:
      #   - mountPath: "/usr/share/nginx/html"
      #     name: www
      # volumes:
      # - name: www
      #   persistentVolumeClaim:
      #     claimName: example-local-claim

---

apiVersion: v1
kind: Service
metadata:
  name: local-pvc
spec:
  selector:
    app: local-pvc
  type: NodePort
  ports:
  - port: 80
    targetPort: web
    nodePort: 30196
  